# Generated by Django 3.0.1 on 2020-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0002_auto_20200324_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
