# Generated by Django 3.0.1 on 2020-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0003_auto_20200403_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_journey',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_of_journey',
            field=models.DateTimeField(default=None, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
