# Generated by Django 3.0.1 on 2020-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0004_auto_20200403_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_of_journey',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_of_journey',
            field=models.DateField(default=None, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=None, help_text='Please use the following format: <em>HH:MM:SS</em>.'),
        ),
    ]
