# Generated by Django 3.0.1 on 2020-04-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0005_auto_20200403_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabshare.Booking')),
            ],
        ),
    ]
