# Generated by Django 3.0.1 on 2020-04-10 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
