# Generated by Django 3.0.1 on 2020-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0009_chat_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_on',
        ),
    ]
