# Generated by Django 3.0.1 on 2020-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0014_chat_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='starting_point',
            field=models.CharField(choices=[('1', 'IIT GUWAHATI'), ('2', 'A'), ('3', 'B'), ('4', 'C'), ('5', 'D'), ('6', 'E'), ('7', 'F'), ('8', 'G')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('1', 'IIT GUWAHATI'), ('2', 'A'), ('3', 'B'), ('4', 'C'), ('5', 'D'), ('6', 'E'), ('7', 'F'), ('8', 'G')], default='1', max_length=100),
        ),
    ]
