# Generated by Django 3.0.1 on 2020-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0016_auto_20200503_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop',
            field=models.BooleanField(default=False),
        ),
    ]
