# Generated by Django 3.0.1 on 2020-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0017_booking_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='going_together',
            field=models.IntegerField(default=0),
        ),
    ]
