# Generated by Django 3.0.1 on 2020-03-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('hostel', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Gender')),
            ],
        ),
    ]
