# Generated by Django 3.0.1 on 2020-03-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_gender_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('hostel', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Gender')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
