# Generated by Django 3.0.1 on 2020-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
