# Generated by Django 3.0.1 on 2020-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200308_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='filled_details',
            field=models.BooleanField(default=False),
        ),
    ]
