# Generated by Django 3.0.1 on 2020-03-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_profile_filled_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='filled_details',
        ),
    ]
