# Generated by Django 3.0.1 on 2020-03-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_profile_filled_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
