# Generated by Django 3.0.1 on 2020-03-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_profile_is_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_filled',
        ),
    ]
