# Generated by Django 3.0.1 on 2020-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_profile_is_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
